# Generated by Django 2.0.2 on 2018-03-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cuenta', models.CharField(max_length=8)),
                ('Nombre', models.CharField(max_length=35)),
                ('Ap_paterno', models.CharField(max_length=35)),
                ('Ap_materno', models.CharField(max_length=35)),
                ('Edad', models.IntegerField(max_length=2)),
                ('FechaNacimiento', models.DateField()),
                ('Sexo', models.CharField(choices=[('F', 'Fememino'), ('M', 'Masculino')], default='M', max_length=1)),
            ],
        ),
    ]
